### ISSUE TITLE
compiler issue

### ISSUE THREAD

**Issue by antoinefalisse** [stanfordnmbl/opencap-processing#113]
Seems like it is not picking the good compiler by default when installing Visual Studio 2022. Check if there is a way to identify the compiler on the computer and specify it in the cmake calls.

Manual fix:

- Change [this line](https://github.com/stanfordnmbl/opencap-processing/blob/main/UtilsDynamicSimulations/OpenSimAD/utilsOpenSimAD.py#L1706) to `cmd1 = 'cmake "' + pathBuildExpressionGraph + '" -G "Visual Studio 17 2022"  -A x64 -DTARGET_NAME:STRING="' + filename + '" -DSDK_DIR:PATH="' + SDK_DIR + '" -DCPP_DIR:PATH="' + CPP_DIR + '"'`
- Change [this line](https://github.com/stanfordnmbl/opencap-processing/blob/main/UtilsDynamicSimulations/OpenSimAD/utilsOpenSimAD.py#L1799) to `cmd3 = 'cmake "' + pathBuildExternalFunction + '" -G "Visual Studio 17 2022" -A x64 -DTARGET_NAME:STRING="' + filename + '" -DINSTALL_DIR:PATH="' + path_external_functions_filename_install + '"' `

Also clean up the folders when an attempt failed

**Comment by antoinefalisse** [comment]
Are you sure you that the C++ development workload is installed? Open the Visual Studio Installer and make sure the "Desktop development with C++" workload is selected and installed.

**Comment by rcknowles04** [comment]
Hi, I appreciate your response. The issue ended up being related to my file path length where I had the git hub repository cloned. Once I enabled my machine to allow longer path lengths (greater than 260 characters) everything compiled just fine! Kind of a strange issue... but everything seems to be working for me now.
