### ISSUE TITLE
Squat analysis

### ISSUE THREAD

**Issue by antoinefalisse** [stanfordnmbl/opencap-processing#118]
- [x] Segmentation: the algo assumes the end of a squat is the beginning of the next one. This isn't good if there are long pauses between reps, should identify beginning and end independently.
- [x] Single leg squat: identify leg of interest
   - [x] Separate left/right leg metrics
   - [x] Only calculate ipsilateral leg for single leg
- [x] Trunk lean wrt ground
- [x] Trunk lean wrt pelvis
- [x] KA [if available](https://github.com/stanfordnmbl/opencap-processing/blob/kam_kinetics/UtilsDynamicSimulations/OpenSimAD/mainOpenSimAD.py#L476-L490)
- [ ] ankle eversion (check Matt DeMers study)
- [x] integrate into web app

[Some squats for testing](https://app.opencap.ai/session/1b380cb9-3c5c-498c-bc30-a1a379ffa04c)

**Comment by carmichaelong** [comment]
Model from [DeMers study](https://simtk.org/frs/?group_id=1027) has a different definition for subtalar than the opencap models. Would need to see if it's good enough as is, or if it'd be important to update the definition.

Can table ankle eversion for now, unless it comes up as a major need.
