### ISSUE TITLE
The problem about the gait analysis coding

### ISSUE THREAD

**Issue by 60502Gary** [stanfordnmbl/opencap-processing#128]
Hello, We have some problem with the example gait analysis code of analyzing gait: We don't know which file format to choose to input for run this code.

And we want to use the data from OpenCap software for calculating the some kinematic parameters, such as gait cycle, step length, stride length, and stride width. Can the example gait analysis code calculate these parameters? 

Thank you

**Comment by 60502Gary** [comment]
https://github.com / stanfordnmbl/opencap-processing /blob/main/Examples/example_gait_analysis.py 

This the code what I mentioned.

**Comment by antoinefalisse** [comment]
All you need it passing [the session id and trial name](https://github.com/stanfordnmbl/opencap-processing/blob/main/Examples/example_gait_analysis.py#L44-L45), You can see [here](https://github.com/stanfordnmbl/opencap-processing/blob/main/Examples/example_gait_analysis.py#L51-L52) some of the variables that you can get. Take a look at [the class](https://github.com/stanfordnmbl/opencap-processing/blob/main/ActivityAnalyses/gait_analysis.py) to see all the variables.
