### ISSUE TITLE
Question about Mocotrack example

### ISSUE THREAD

**Issue by InckieUltra** [stanfordnmbl/opencap-processing#130]
Hi, I notice that the moco track example says it would take 5 hours. I wonder if its normal to solve a problem with moco track?

**Comment by carmichaelong** [comment]
Thanks for your question. The GitHub repository is Issues are for tracking development issues. For general questions, please post on the OpenCap forum: https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=2385
