### ISSUE TITLE
example.ipynb

### ISSUE THREAD

**Issue by annatudse** [stanfordnmbl/opencap-processing#42]
**Installing opensim, condacolab the sourcecode from github runs without problems on colab. I ran it directly and aslo made copy to an colab notebook version which gives me the same error.**
![image](https://user-images.githubusercontent.com/102486735/206294222-94b5a3c5-6746-45af-8e17-830853d3daa9.png)
![image](https://user-images.githubusercontent.com/102486735/206294680-8960ffc2-1b7a-4c99-b9e6-af98990e9f41.png)

**I get following errors when importing packages** 
ModuleNotFoundError Traceback (most recent call last)
[<ipython-input-5-7cbd38586d2c>](https://localhost:8080/#) in <module>
      1 import os
----> 2 import utilsKinematics
      3 from utils import download_kinematics
      4 from utilsPlotting import plot_dataframe

[/content/opencap-processing/utilsKinematics.py](https://localhost:8080/#) in <module>
     20 
     21 import os
---> 22 import opensim
     23 import numpy as np
     24 import pandas as pd

ModuleNotFoundError: No module named 'opensim'

![image](https://user-images.githubusercontent.com/102486735/206302919-8b66b5f4-d2f1-43a8-9ee9-c5f6a724ae93.png)

**Comment by annatudse** [comment]
Could it have anything to do with this?  It seems that two copies of opencap-processing exist?
<img width="334" alt="image" src="https://user-images.githubusercontent.com/102486735/206307431-2157ca6c-7684-49a3-ae8e-17767e3bbcd3.png">

**Comment by aymanhab** [comment]
Does this have to do with python version on jupyter going up to 3.8? I'm having issues with the generic opensim notebooks that look kinda similar. Switching to opensim_admin to force using 3.8 conda package instead of opensim-org fixes the issue for now (until we can sort things out), can you test? Thank you

**Comment by annatudse** [comment]
Should i write _!conda install -c opensim_admin opensim_ instead of _!conda install -c opensim-org opensim_  in colab?

**Comment by antoinefalisse** [comment]
Yes, [I corrected for it already](https://github.com/stanfordnmbl/opencap-processing/commit/680bc17f6be159f8b057fbfa48a2e325e7559ea7). But if you somehow made a copy of the colab beforehand then that is what you should do

**Comment by aymanhab** [comment]
Thanks @antoinefalisse that change was for testing purposes but I actually updated the conda package for opensim-org so the correct version should be pulled now. I'd revert the change (restore use opensim-org) and let me know if you see problems. Thank you

**Comment by antoinefalisse** [comment]
Thanks @aymanhab, I reverted.

@annatudse the bug has been fixed, so you should be able to use the original script with opensim-org. Let us know if you run into issues.

**Comment by annatudse** [comment]
And voila :)
![image](https://user-images.githubusercontent.com/102486735/206786600-f0547313-f555-4329-bc0d-7737b8203a56.png)
Thanks @antoinefalisse @aymanhab :)

**Comment by antoinefalisse** [comment]
The bug was on the opensim side - nothing to do with you. Thanks for reporting that it didn't work.
