### ISSUE TITLE
certificate verify failed & urlopen error when running example_kinetics.py

### ISSUE THREAD

**Issue by jadehebmc** [stanfordnmbl/opencap-processing#46]
I followed the tutorial and did the set-up as instructed. The example.py ran successfully. Immediately, I tried running example_kineitcs.py, these two errors occurred:

![Capture2](https://user-images.githubusercontent.com/44212939/210022751-7beeb3ed-5696-4288-8909-0e4d3d5126b3.PNG)
![Capture3](https://user-images.githubusercontent.com/44212939/210022752-e7110656-664e-4cec-a272-5e701b527cb2.PNG)

**Comment by jadehebmc** [comment]
I created a new conda environment and reinstalled all the packages. Tried again. example.py ran successfully, but not example_kinetics.py for the same errors.
[error.txt](https://github.com/stanfordnmbl/opencap-processing/files/10322678/error.txt)

**Comment by antoinefalisse** [comment]
@jadehebmc thanks for reporting. I will try to debug next week. Are you on Windows? Are you are connected to internet? It is failing to download some third-party libraries.

Here is a temporary workaround:
1. Download the folder with the libraries manually: https://sourceforge.net/projects/opensimad/files/. Make you sure you download the right libraries based on your platform (eg, windows.zip).
2. In the UtilsDynamicSimulations\OpenSimAD folder of opencap-processing, create a subfolder and name it OpenSimAD-install. 
3. Extract the downloaded folder in that subfolder. You should now have something like: 
![image](https://user-images.githubusercontent.com/19328993/210033964-2cd04005-199b-4c0d-a8d8-16acea4f9d34.png)
4. Re-run example_kinetics.py. Now that the libraries are in your local repository, it will not try to downalod them, and the script should run smooth.

Let me know if you still run in to issues.

**Comment by jadehebmc** [comment]
@antoinefalisse thank you. I am on windows and connected to internet. After downloading the files, I was able to run example_kinetics.py on my original (older) computer. I also tried on a different windows computer (newer) and did not encounter this issue (would that be an issue with my computer instead of the code?)

**Comment by antoinefalisse** [comment]
Great, thanks for letting me know. I will investigate this further, and keep you posted.

**Comment by antoinefalisse** [comment]
@jadehebmc we pushed a fix for this bug, hopefully it works on your machine. Let us know otherwise. Thanks.
